version: '3.8'

services:

  #::======================================================>> PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: boilerplate-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: boilerplate-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
